---
- name: Installing EPEL release
  yum:
    name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
    state: 'present'

- name: Installing CentOS specific Pre-Reqs
  yum:
    name: "{{ item }}"
    state: "present"
  when: ansible_distribution == 'CentOS'
  with_items:
    - 'python-crypto'

- name: Installing RHEL specific Pre-Reqs
  yum:
    name: "{{ item }}"
    state: "present"
  when: ansible_distribution == 'RedHat'
  with_items:
    - 'python-cryptography'
    - 'python-devel'

- name: Installing Common Pre-Reqs
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - 'git'
    - 'libffi-devel'
    - 'openssl-devel'
    - 'python-devel'
    - 'python-setuptools'
    - 'gcc'

- name: Installing Python-Pip
  yum:
    name: "python-pip"
    state: "present"
  when: ansible_distribution == 'CentOS'

- name: Installing Python-Pip
  yum:
    name: "python2-pip"
    state: "present"
  when: ansible_distribution == 'RedHat'

